### PR TITLE
remove jp2 references from tutorial images

### LINKED ISSUE #178: Remove jp2 references from tutorial images
This issue is a good option for someone who is contributing to the project for the first time or contributing to open source for the first time.  The instructions below assume you have some familiarity with developing software.

In a previous issue, we updated the text of the fusion tutorial to use .tif images instead of .jp2 images.  However, the images in the tutorial still show users selecting .jp2 images.  For example, see step 6 under "Define Imagery Resources" on this page: http://www.opengee.org/geedocs/answer/4412443.html.  We need to update the images to show .tif files instead of .jp2 files.

Tips for working this issue:
- Join our slack channel at http://slack.opengee.org/ and ask lots of questions.
- The instructions below don't have a complete description of how to use git and github.  If you need help with that, please ask.
- Ignore the conversation below about this ticket - it's mostly irrelevant now.
- If you don't have time to change all of the images, just do a few of them (or even just one) and submit a pull request.  Any fix will help.

Steps to fix this issue:
1. Build and install Fusion and GEE Server by following the instructions here: https://github.com/google/earthenterprise/wiki/Build-Instructions and here: https://github.com/google/earthenterprise/wiki/Install-Fusion-or-Earth-Server.  We recommend installing VirtualBox, then creating a VM, then installing Ubuntu 14.04 in that VM, then installing Fusion and GEE Server on the VM.
1. Create a branch in your git repo to work on.
1. Look through all of the basic tasks and advanced tasks in the fusion tutorial.  The tutorial starts here: http://www.opengee.org/geedocs/answer/4412440.html.  Find all the images that show .jp2 files, like the one below:
image
1. Create new images for each affected image that show .tif files instead of .jp2 files.  You can do this with any screen shot tool.
1. Replace the relevant images under earthenterprise/docs/geedocs/art/fusion/tutorial with your new images.
1. Commit your changes and submit a pull request.

### PR DESCRIPTION
**Pull request by anu0012**
Fixes #178

### CODE REVIEW

**Comment by bradh** [comment]
While this is probably a valid fix, I think you missed the part about updating the image (i.e. pictures). As an example:
http://www.opengee.org/geedocs/art/fusion/tutorial/imageryOpen-BM.png

**Comment by anu0012** [comment]
Hey, @bradh I am a mac user and earth enterprise is not compatible for mac. Do I need to install it on a Ubuntu machine and take screenshots from there?

**Comment by tst-ccamp** [comment]
Hey @anu0012, this is likely going to conflict with https://github.com/google/earthenterprise/pull/184. We currently have copies of the documentation on 2 different branches, one for opengee.org and one to be installed locally. We're trying to come up with a good solution to keep them in sync with each other. I believe this issue with the text was already corrected on the other branch (gh-pages). So, the main purpose of #178 was to get new screen grabs. 

To answer your question, yes you'll need to install Fusion on an Ubuntu or CentOS VM in order to get the new screenshots. Sorry for any confusion here. Please don't hesitate to ask any follow-up questions and you are welcome to join our slack channel by going to http://slack.opengee.org/

**Comment by anu0012** [comment]
Hey, @tst-ccamp Thanks for the help. I've created VM on my system but I am facing some problem with the installation. I followed the instructions given in the wiki but I am getting few errors. Can you please help me?

**Comment by bradh** [comment]
@anu0012 Suggest coming over to the slack site to discuss (see links on wiki) or at least posting the error. We can help, but obviously we're going to need much more detail on what the problem is.

**Comment by tst-ccamp** [comment]
@anu0012 These changes should have been addressed by https://github.com/google/earthenterprise/pull/184. I'm going to close this PR. If you have any updates for the images please feel free to open a new one.

**Pull request closed without merging**
