### PR TITLE
WIP: code to test xml reads/writes with

### PR DESCRIPTION
**Pull request by tst-basilhuffman**

### CODE REVIEW

**Comment by tst-basilhuffman** [comment]
I wasn't worried about termination in this pr. It shouldn't call it from this pr

**Comment by tst-lsavoie** [comment]
Oops - posted on the wrong PR.

**Comment by tst-basilhuffman** [comment]
@tst-lsavoie should i go ahead and close this one out?

**Comment by tst-lsavoie** [comment]
IIRC we decided not to merge this, correct? I think it's ready to close out.

**Comment by tst-basilhuffman** [comment]
Ok, I've got it

**Pull request closed without merging**
