### PR TITLE
Remove old scripts for creating Portable Globe Server installers.

### LINKED ISSUE #143: Remove obsolete portable server install scripts
https://github.com/google/earthenterprise/blob/master/earth_enterprise/legacy_installer/Scripts/portable/create_linux_installer.sh is broken post unbundling of python.

We already have a replacement in https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/portableserver/build.py

### PR DESCRIPTION
**Pull request by bradh**
This code is replaced by https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/portableserver/build.py and is no longer functional after unbundling of python

Resolves #143

### CODE REVIEW

**Comment by asmitaw** [comment]
looks good.

**Comment by andreisel** [comment]
Have assigned to @tst-ppenev for reviewing/approval, since he's worked on the Portable installer.

**Comment by tst-ppenev** [comment]
We could possibly also remove the \<earthenterprise/earth_enterprise/legacy_installer/Scripts/portable/windows-installer\> directory, as well. I don't think anyone has tested the new Python script on Mac, so we can leave that part around.

**Comment by tst-ppenev** [comment]
@bradh: I can't find your comment, but, yes, I vote for removing the Windows and the Linux directories. I don't think they're doing much good, and may cause confusion. I'd even approve removing the Mac directory, since it's also obsolete, and I don't think anyone would look at it when testing and fixing the Mac installer.

Since no one has objected, I'd say, let's just remove them.

I welcome any objections.

**Comment by tst-ccamp** [comment]
@tst-ppenev @bradh I have no issue with just removing them all. If we need to refer to them, we can always look back at the history.

**Comment by tst-ppenev** [comment]
:cool: We can rename the ticket to something like 'Remove old Portable Server installer creation scripts', or whatever sounds more human.

**Comment by bradh** [comment]
OK. Will catch up with that tonight.

**Comment by tst-ppenev** [comment]
Thanks, @bradh. I'll update the title with something temporary.

**Comment by bradh** [comment]
Should be completely removed now. Suggest squash on merge.

**Comment by tst-ppenev** [comment]
@tst-ccamp, @avnishb, @asmitaw, @andreisel: Do you know if the icons under locations, such as under \<`earthenterprise/earth_enterprise/legacy_installer/Scripts/portable/windows-installer/server_extra/`\> can be used in GEE Open Source?

**Comment by tst-ppenev** [comment]
@bradh: This looks fine to me. I'm just wondering if we want to keep the icons for possible use in future installers.

**Comment by bradh** [comment]
@tst-ppenev They can always be pulled out of the history as of the previous commit:
https://github.com/google/earthenterprise/tree/d91a2b8daf899e31e301041db2dc182c7c9b46ee/earth_enterprise/legacy_installer/Scripts/portable/windows-installer/server_extra/icons

**Comment by tst-ppenev** [comment]
@bradh: This issue seems to require agreements among people who we may not hear from immediately. My vote is to move the \<`server_extra`\> directory under \<`earth_enterprise/artwork`\> for now, and remove the rest of the portable legacy installer generators.

**Comment by bradh** [comment]
@tst-ppenev: OK. Abandoning this attempt. Can you update the original ticket (#143) with what you really want to happen?

**Pull request closed without merging**
