### PR TITLE
Issue #1104 - OpenGEE Build Fails on Centos 7

### PR DESCRIPTION
**Pull request by tst-eclamar**
This bug is due to an update of Centos 7 from "7.5" to "7.6" - libpng15 is added in "7.6", and is incompatible with libpng12.

### CODE REVIEW

**Comment by tst-nfarah** [comment]
Let's add a description for this PR and also target release_5.2.5 branch as the branch to merge to. We likely want to merge that branch into master as soon as the this PR was approved.

**Comment by tst-ccamp** [comment]
OK, I have an idea that might simplify this. This is really the better solution, but we only want to do it if we can find the file. So maybe add a comment to say that this is a fix for CentOS & RHEL 7 and add a check to see if the file is there before adding the symlink and then that should be good enough.

**Comment by tst-ccamp** [comment]
After the update, I tested on RHEL 7 and it worked fine. I'm going to go ahead and approve pending a successful test on RHEL 6

**Comment by tst-ccamp** [comment]
This update passed on RHEL 6, CentOS 6, and Ubuntu 16.04 also. So, merging.

**Pull request merged**
