### PR TITLE
Add IsUpToDate function for SharedStrings

### PR DESCRIPTION
**Pull request by lacrosse91**
Hi.
Addresses #1842 and add IsUpToDate function for SharedStrings.
This PR is for a performance change.

### CODE REVIEW

**Comment by lacrosse91** [comment]
@googlebot I signed it!

**Comment by tst-lsavoie** [comment]
Thanks for the PR @lacrosse91. The code looks good, but we'll need to do some testing before we merge it.

**Comment by lacrosse91** [comment]
Thanks for review, @tst-lsavoie.
I would appreciate if you could tell me what I have to do.

**Comment by tst-lsavoie** [comment]
@lacrosse91 you don't need to do anything right now. I want to do some testing on my end before giving a final approval.

**Comment by lacrosse91** [comment]
Thanks for reply.
I'm very happy to contribute to this great project.

**Review by tst-lsavoie — APPROVED** [review]
I ran some tests and everything looks good. I also verified that the new function is being called. There seems to be a small performance improvement as expected, though the difference is slight so it's hard to be sure.

We'll need a second reviewer before merging this PR. I've asked one of my colleagues to do it. We should get it done today or early next week.

**Review by tst-jlarocco — APPROVED** [review]
Looks good!  Thank you @lacrosse91!

**Pull request merged**
