### PR TITLE
Merge 5.3.3 to master

### PR DESCRIPTION
**Pull request by tst-lsavoie**

### CODE REVIEW

**Comment by tst-lsavoie** [comment]
All commits were previously included in this repo, so there are no CLA issues.

**Comment by Rustypp** [comment]
> All commits were previously included in this repo, so there are no CLA issues.

How or where do you get support for Google Earth Enterprise by support I mean talk to a human using Forums software NOT someone giving you links to the docs have read the docs did not find my answers in the docs.

Sorry for asking here his is the only thing I have found on GitHub where you can leave a message to someone who works on Google Earth Enterprise. NOT sure how or if I will be notified of your reply.

Thanks in advance

**Comment by Rustypp** [comment]
So I commented here a few minutes ago and could read my comment, I refreshed this page to see if bookmarking this page would allow me to return and look for replies to my comment and I cannot find my last comment

Can someone explain how these comments work I have spent hours trying to figure it out, read the docs I just do not get it OR detailed instructions on how to collaborate with other GitHub members I have many questions about Google Earth Enterprise that are not answered in the GEE documentation there has to be Google Earth Enterprise Support Forums some place???

FYI NO SUPPORT is given here https://groups.google.com/forum/#!forum/google-earth-enterprise its DEAD people must be using something else for support? 

The Slack Chatroom webpage loads BLANK http://slack.opengee.org 

Thanks in advance

**Comment by Rustypp** [comment]
How do you find comments you have made at GitHub in the past to see if someone has replied, are you notified by email I went into my GitHub Profile and found nothing, are GitHub members/users not allowed to communicate with each other, what am I missing here?

**Comment by tst-basilhuffman** [comment]
@Rustypp the slack channel is not slack.opengee.org, it is opengee.slack.org

**Comment by tst-lsavoie** [comment]
@Rustypp I'm going to try to answer all the questions you posted here, though not necessarily in order.

1. It would help us a lot if you posted details about the problem you are having. Without a better understanding of what is not working for you we can't help you very much.

2. Support is provided by volunteers through users and developers helping each other. Open GEE is a relatively small open source community, so sometimes it takes us a few days to respond. You can get support through https://groups.google.com/forum/#!forum/google-earth-enterprise (which is not dead, believe it or not, just slow sometimes) or via the slack channel. As you pointed out, the link to http://slack.opengee.org is currently broken, which we are working on. If you give me an email address to use, I can send you an invite to the slack channel.

3. If you have asked for support previously and only gotten a link to some docs, it's probably because whoever posted the link thought it would help you. If it didn't help, you're welcome to post a reply explaining why it didn't help and a detailed description of the support you need.

4. As far as getting notifications about replies to GitHub comments, I usually get emails from GitHub about replies to my comments. If that isn't working for you I'd suggest checking that your email address is correct and that the messages aren't being sent to spam. I can't really help beyond that since I don't have any control over how GitHub works.

The main thing is to post details about the problems you are having. You mentioned that you have many questions about Open GEE, but I don't see your questions posted anywhere. If you post your specific questions, either here, on the forums, or in slack, we will do our best to help you.

**Comment by Rustypp** [comment]
Basil 
Thanks for the reply, I cut and paste the link slack.opengee.org located at the bottom of this web page https://github.com/google/earthenterprise/wiki if we had a direct line of communication with the folks at GEE who maintain that page I could report the error to them.

The link you provided opengee.slack.org does not work either, did you try that link, right at the top of the page it says "Domain for sale. Call +1 339-222-5134 or click here to make an offer " 

Can someone explain how were suppose to collaborate communicate with other GitHub users or more importantly with the good people working on the google/earthenterprise project directly?

I have found really good tutorials on how to use GEE I have not found a single step by step tutorial on installing GEE that work, also no place to discuss errors received when trying to install GEE

I started setting up forums here http://www.pilotodyssey.com/GE/index.php but am not sure how to share the link with others sharing the same interest in GEE 

Thanks again.

**Comment by tst-basilhuffman** [comment]
@Rustypp try https://opengee.slack.com (not slack.org)

**Comment by Rustypp** [comment]
> @Rustypp I'm going to try to answer all the questions you posted here, though not necessarily in order.
> 
>     1. It would help us a lot if you posted details about the problem you are having. Without a better understanding of what is not working for you we can't help you very much.

I installed this on Ubuntu 16.04.6 LTS https://github.com/google/earthenterprise/blob/1f6f5850a54dd620b07553eafa4afbc4affbec17/earth_enterprise/BUILD_Ubuntu.md  and received no errors 

Next I went to this page https://github.com/google/earthenterprise/wiki/Portable-Server

I made it to the step **earthenterprise/earth_enterprise/src/portableserver/build.py** it returned this error **bash: earthenterprise/earth_enterprise/src/portableserver/build.py: No such file or directory**

Now what?

**Comment by tst-lsavoie** [comment]
You probably need to run it from your home directory. Try running `cd` and then running `earthenterprise/earth_enterprise/src/portableserver/build.py` again.

**Comment by Rustypp** [comment]
I entered the command **cd earthenterprise/earth_enterprise/src/portableserver/build.py** it returned this error **bash: cd earthenterprise/earth_enterprise/src/portableserver/build.py: No such file or directory**

Now what?

**Comment by tst-lsavoie** [comment]
Try it as two separate commands: `cd`, then press enter, then the build command.

**Comment by Rustypp** [comment]
> @Rustypp try https://opengee.slack.com (not slack.org)

That link works thanks, however I do not have an account noticed at the bottom it says **Don't have an account on this workspace yet?Contact the workspace administrator for an invitation**

I  do not know where is the workspace administrator no links are given, its just assumed we know?
I did watch the first 60 seconds of the video  https://www.youtube.com/watch?time_continue=4&v=6c7_TpPUpL0&feature=emb_logo and I dont think Slack is for me I am just looking for detailed installation instruction to install GEE server so I can cache date for use in the Desert without a internet connection.

Thanks

**Comment by Rustypp** [comment]
> Try it as two separate commands: `cd`, then press enter, then the build command.

**$ cd
$ cd earthenterprise/earth_enterprise/src/portableserver/build.py** it returned this error **bash: earthenterprise/earth_enterprise/src/portableserver/build.py: No such file or directory**

Suggestions?
Thanks

**Comment by tst-lsavoie** [comment]
Let me take a step back and see if I understand your use case. It sounds like you want to have access to some kind of map or globe data without an internet connection. Open GEE can do that for you. The second important question is, do you have your own imagery data that you want to use? The idea behind Open GEE is that it lets you take your own data (imagery, terrain, whatever) and build it into a globe that you can browse similar to Google Earth. However, Open GEE doesn't provide the data you need to build your maps, just the software. If you want to take Google's map data in an offline environment, Open GEE won't do that for you.

**Comment by tst-lsavoie** [comment]
On the build error, you need to find the directory where you downloaded Open GEE. Go to wherever your earthenterprise directory is, then go up one directory (you can use the command `cd ..` to do that), then try the build command.

Alternatively you can run `cd ; find . -name earthenterprise` and post the results and that may tell us where you downloaded it.

**Comment by Rustypp** [comment]
I do not have my own data I was going to get the data from Google Earth.

Actually all I need is a Google Earth Portable like seen here http://portableappz.blogspot.com/search?q=google+earth+ that does not have a 2 GB cache limit, I tried using multiple installations and caching the data at home staying below the 2GB limit but when I get offline half the time GE will not launch because it can not connect to the GE server then when it does sometimes the cached data does not load. 

Thanks.

**Comment by Rustypp** [comment]
This is what I need https://www.youtube.com/watch?v=UHL9sDbBGnk

**Comment by tst-lsavoie** [comment]
It sounds like Open GEE won't work for your case. It can do everything you need except provide the map data. Google doesn't provide their data to us, and I don't know of any way they let the general public access it without an internet connection.

You could try downloading the latest version of the Earth Client: https://github.com/google/earthenterprise/wiki/Google-Earth-Enterprise-Client-(EC). If you open that and go to Tools -> Options -> Cache you can increase the Disk Cache Size. Google does provide a default globe at http://kh.google.com/, so you may be able to cache what you need from there. However, I have no idea if it will work for you. You may run into the same problems that you had with the portable earth client you referred to earlier.

Another option is to try to find freely available data and build your own globe. There are lots of resources online that provide data, such as https://earthexplorer.usgs.gov/. Some others are listed here: https://github.com/google/earthenterprise/wiki/Shared-GEE-Assets. Building a globe can be a fairly involved and complicated process, though, so it may not be pleasant for you.

**Comment by Rustypp** [comment]
> On the build error, you need to find the directory where you downloaded Open GEE. Go to wherever your earthenterprise directory is, then go up one directory (you can use the command `cd ..` to do that), then try the build command.
> 
> Alternatively you can run `cd ; find . -name earthenterprise` and post the results and that may tell us where you downloaded it.

I am confused am following the instructions located here https://github.com/google/earthenterprise/wiki/Portable-Server I thought the command **earthenterprise/earth_enterprise/src/portableserver/build.py** I thought that command was to download the file, the instructions on that page are foggy at best?

**Comment by Rustypp** [comment]
> It sounds like Open GEE won't work for your case. It can do everything you need except provide the map data. Google doesn't provide their data to us, and I don't know of any way they let the general public access it without an internet connection.
> 
> You could try downloading the latest version of the Earth Client: https://github.com/google/earthenterprise/wiki/Google-Earth-Enterprise-Client-(EC). If you open that and go to Tools -> Options -> Cache you can increase the Disk Cache Size. Google does provide a default globe at http://kh.google.com/, so you may be able to cache what you need from there. However, I have no idea if it will work for you. You may run into the same problems that you had with the portable earth client you referred to earlier.
> 
> Another option is to try to find freely available data and build your own globe. There are lots of resources online that provide data, such as https://earthexplorer.usgs.gov/. Some others are listed here: https://github.com/google/earthenterprise/wiki/Shared-GEE-Assets. Building a globe can be a fairly involved and complicated process, though, so it may not be pleasant for you.

How about using sas.planet to build the globe?

**Comment by Rustypp** [comment]
> > It sounds like Open GEE won't work for your case. It can do everything you need except provide the map data. Google doesn't provide their data to us, and I don't know of any way they let the general public access it without an internet connection.
> > You could try downloading the latest version of the Earth Client: https://github.com/google/earthenterprise/wiki/Google-Earth-Enterprise-Client-(EC). If you open that and go to Tools -> Options -> Cache you can increase the Disk Cache Size. Google does provide a default globe at http://kh.google.com/, so you may be able to cache what you need from there. However, I have no idea if it will work for you. You may run into the same problems that you had with the portable earth client you referred to earlier.
> > Another option is to try to find freely available data and build your own globe. There are lots of resources online that provide data, such as https://earthexplorer.usgs.gov/. Some others are listed here: https://github.com/google/earthenterprise/wiki/Shared-GEE-Assets. Building a globe can be a fairly involved and complicated process, though, so it may not be pleasant for you.
> 
> How about using sas.planet to build the globe?
I have Google Earth Client 7.3.2.5776 (64-bit) installed on Linux Mint it still only allows you to Cache 2048MB of data just like the portable versions

I watched the Google Earth Enterprise Essentials 14 part video series on YouTube narrated by Mike Imhoff (not sure of the last name spelling) building globes does not seem that complicated compared to installing the server on a computer, its kinda frustrating they created a 14 part video series detailing how to use GEE but do not offer equally detailed installation instructions.

**Comment by tst-lsavoie** [comment]
I'm not familiar with sas.planet. It may work.

It's true that building a globe isn't that complicated. It can be a bit much for someone that hasn't spent a lot of time working with GIS systems, particularly if you want multiple layers like imagery, terrain, road data, etc.

The `earthenterprise/earth_enterprise/src/portableserver/build.py` command is to build portable server. The file build.py should already be there, and all you're trying to do is run the file. Have you previously downloaded Open GEE?

**Comment by Rustypp** [comment]
I am so confused at this point I really have no clue if I downloaded Open GEE or not I am just following steps on web pages I have found that are related to installing GEE

How would I find out if I downloaded Open GEE or not what page would have the instructions what, would the downloaded file name be, I could search my computer for the file then move it to the correct directory? 

I still have no clear picture how to install GEE I think I am just guessing to be honest, I find myself jumping all over the place with distractions like joining GitHub and spending hours trying to figure out where how to ask questions rather than just joining a PHPBB style modern forums you can search or browse reading archived topics, if someone would write a tutorial with the steps required to install in a simple HTML or PDF format detailing the installation assuming the installer knows nothing about installing the required software.. 

I am sure you have installed software in Ubuntu or Windows, a precise link is is defined, you download the file, it lands in the Downloads folder, you double click on the file and it installs on your system OR In Linux Terminal type  **sudo apt-get install cherrytree** Enter your password when asked, you will find the link to start Cherrytree in no hair pulling required 

Most the instructions I struggle with could be simply clarified if the author just used a few more words in each work step.


Thanks again.

**Comment by tst-lsavoie** [comment]
As a starting point, I'd recommend carefully running through the steps in https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD.md again, making sure to follow the link for your version of Linux in step 1 and follow those steps as well. Once you get through that successfully it will be easier to move forward.

Unfortunately we don't have a simple installer. That's one of the downsides of freely provided open source software - some things that would be useful don't end up high enough on the priority list to get worked.

**Comment by Rustypp** [comment]
I thought I struck gold when I found this video https://www.youtube.com/watch?v=KhFYr5b8MpE&t=3s but only 38 seconds in the gold turned to crap when she has you downloading something unknown "You can clone it" what ever "IT" is  she does mention "After you have Git Installed" so did I just download and install "Git" from the google/earthenterprise GitHub page? I thought you cant download anything unless you have a GitHub account? I have literally watched the first 1 minute of the video 7 times and have tons of questions nothing makes any sense, then she starts typing in Terminal and I cant see the first 5 lines they are cut off because she maximized Terminal window and the font is 20x too small 

How can I contact " geogis tech" she a GitHub member at 28 seconds she says "our GitHub Page" ? NO contact link provided in the video description 
At 1:03 she says this is the command I ran to get my clone setup. Clone of what, what was the command you cant see it in the video?

More confusion

**Comment by tst-lsavoie** [comment]
I'd recommend starting here: https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD.md. That will include everything, such as installing Git, cloning, etc. I think that's one of the better guides we have - it should be fairly step by step and exact. If you run into trouble while going through it, let me know.

**Comment by Rustypp** [comment]
Thanks I will give it a try, first question do I want to build a Earth Enterprise Fusion and Server or build and install a Portable server?

**> Building Earth Enterprise Fusion and Server
> NOTE: If you want to build, install, or run Portable server, see the Portable Server page.**

**Comment by Press1** [comment]
Made it to here on this page https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD.md

**Method 2: Clone and download LFS files in two steps:

GIT_LFS_SKIP_SMUDGE=1 git clone git@github.com:google/earthenterprise.git
cd earthenterprise**

~ $ GIT_LFS_SKIP_SMUDGE=1 git clone git@github.com:google/earthenterprise.git
Cloning into 'earthenterprise'...
The authenticity of host 'github.com (140.82.114.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.114.3' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by tst-basilhuffman** [comment]
@Press1 this method of cloning assumes you have a ssh key. If you do not, try cloning this way:

`$ GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/google/earthenterprise.git`

**Comment by Press1** [comment]
> GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/google/earthenterprise.git

I had to close Terminal and reopen to make this command work

Same with entering the commands in step 4 had to restart Terminal, whats up with that?



Build Earth Enterprise Fusion and Server:

**cd earthenterprise/earth_enterprise
scons -j8 release=1 build**

**Comment by Press1** [comment]
Ran into a snag installing Fusion https://github.com/google/earthenterprise/wiki/Install-Fusion-or-Earth-Server

/earthenterprise/earth_enterprise/src/installer $ sudo ./install_fusion.sh

Welcome to the Google Earth Enterprise Fusion 5.3.4 installer.

The hostname of this machine does not match the fully-qualified hostname.
 requires that they match for local publishing to function properly.
Exiting the installer.  If you wish to continue, **re-run this command with the -hnmf 'Hostname** Mismatch Override' flag.

DO I re-run the command with the -hnmf 'Hostname Mismatch Override' flag? If so is this the correct command  ` sudo ./install_fusion.sh -hnmf 'Hostname** Mismatch Override'  `

**Comment by tst-lsavoie** [comment]
Generally speaking, you need to build and install Open GEE Fusion and Server somewhere so that you can build your globes and maps. Once you do that, you can make a "cut" file that contains only the data you want to take with you. You then install portable on your laptop and copy the cut file to your laptop, and portable uses that. So you often end up needing Fusion, Server, and portable. That's why I suggested starting with Fusion and Server.

On the install error, the command is simply `sudo ./install_fusion.sh -hnmf`.

**Comment by Rustypp** [comment]
I think I have Fusion and Earth Server installed how do I start and test, browser crash last night closed all my tabs have no clue where I left off 

Thanks

**Comment by tst-lsavoie** [comment]
We have a pretty good tutorial that should help with that: http://www.opengee.org/geedocs/5.3.4/answer/fusionTutorial.html. Even if you just do the first part and make sure you can define and build a resource it will give us an idea of whether Fusion is currently working.

**Comment by Press1** [comment]
I am trying to work through this Configure Tutorial Workspace thing http://www.opengee.org/geedocs/5.3.4/answer/fusionTutorial/confTutorialWS.html

Stuck on `geconfigureassetroot --new --assetroot /username/assets`
**~ $ geconfigureassetroot --new --assetroot /ooo/assets
geconfigureassetroot: command not found**


Thanks
Happy New Years..

**Comment by tst-basilhuffman** [comment]
@Press1 the binaries may not be present in your PATH, so use the fully qualified path i.e. `/opt/google/bin/geconfigureassetroot --new --assetroot /username/assets`

**Comment by Press1** [comment]
Now I am stuck on To select the tutorial asset root:
Enter:
`geselectassetroot --assetroot /username/assets` that didnt work after about half hr of messing around got this command to work sorta. $ /opt/google/bin/geconfigureassetroot  --assetroot /ooo/assets

Error: One of the following options must be specified:
	--addvolume
	--editvolumes
	--fixmasterhost
	--listvolumes
	--new
	--removevolume
	--repair

usage:
  /opt/google/bin/geconfigureassetroot {--new|--repair|--editvolumes|--fixmasterhost|--addvolume|--removevolume|--listvolumes [options]}
Configure this machine to run Google Earth Fusion.
  --help, -?                  Display this usage message

Options:
  --assetroot <dir>           Path to asset root [current: /gevol/assets]
                              It is shown in the commands below as
                              mandatory or optional. If optional, then
                              the current asset root is used if it is
                              not specified.
  --noprompt                  Do not prompt for more information,
                              returns -1 to indicate an error if
                              command fails or has insufficient
                              arguments.
  --nochown                   Do not attempt to fix privileges.
When creating a new asset root, additional options are available:
  --srcvol <dir>              Path to source volume.

Commands:
  --new --assetroot <dir>     Create new asset root in specified
    [--srcvol <dir>]          directory.
  --repair                    Repair various inconsistencies in the
    [--assetroot <dir>]       asset root
  --editvolumes               Follow the prompts to add a volume to the
    [--assetroot <dir>]       selected asset root or, modify the local
                              path definition for an existing volume,
                              or to add a volume definition.
  --listvolumes               List available volumes in the asset root.
    [--assetroot <dir>]
  --fixmasterhost             Change the asset root host entry to match
    [--assetroot <dir>]       the current host name.
  --addvolume <volume_name>:<dir>
    [--assetroot <dir>]       Add a volume with the given name and
                              directory.
  --removevolume <volume_name>
    [--assetroot <dir>]       Remove a volume with the given name.
Why am I performing this step in the first place?

Thanks

**Comment by tst-lsavoie** [comment]
The idea behind creating and selecting a new asset root is so that the data you create during the tutorial doesn't get mixed up with your real data. You can skip this part if you like.

The reason the command failed is because you're using a slightly wrong command: you ran `/opt/google/bin/geconfigureassetroot --assetroot /ooo/assets` but you need to run `/opt/google/bin/geselectassetroot --assetroot /ooo/assets`.

Also, if you log out and log back in that should fix your PATH. Then you can run commands like `geselectassetroot` instead of `/opt/google/bin/geselectassetroot`.

**Comment by Rustypp** [comment]
So the installation instructions should include "log out and log back in before attempting this command" ? I am just following the instructions cut and pasting...

I have to start the whole build/installation all over again, about 20 hrs wasted because Timeshift in Linux Mint created a automatic backup and filled 100% of my hard drive the computer then gave me the black screen of death 5 hrs of searching later I discovered what happen after moving 10 gigs of files off the drive using the boot CD the system restarted but the VM I was using for GEE was corrupted by the Timeshift fiasco.

WHY Timeshift does not calculate required free space before running the backup then notify you there is not enough space OR while running the backup when the drive gets close to full STOP and notify the user is beyond me the whole idea behind Timeshift is Data Preservation, I disabled Timeshift and will NEVER use it again. FYI I had 56 GIG of free space before Timeshift ran the backup.

**Comment by tst-lsavoie** [comment]
Yes, looks like that's a deficiency in our build instructions. I'll take some notes on things to update.

**Comment by Rustypp** [comment]
> Yes, looks like that's a deficiency in our build instructions. I'll take some notes on things to update.

Thank you.

**Pull request merged**
