### PR TITLE
WIP: Fixes #782 migrate fusion hostname

### LINKED ISSUE #782: Provide a Utility for Migrating from One Fusion Hostname to Another
As an Open GEE administrator, I want to have an easy way of changing the hostnames of Fusion servers.

Currently, Fusion hostnames get recorded as part of the published, and pushed database configuration in Server.  If a Fusion hostname changes, all of these databases need to be deleted in Server, re-pushed from the new Fusion host, and re-published.

## AC

* Provide a command-line utility that accepts the old Fusion hostname, and the new Fusion hostname, and, possibly, the Server hostname.
* The utility should update all pushed and published databases on Server that are provided by the old Fusion hostname to use the new hostname.
* The databases that were published using the old Fusion hostname should be accessible by globe or map client after running the utility, and read databases using the new Fusion hostname.
* The utility can require to be run on the Server machine, or to be run on the Fusion machine.
* The utility can require to be run as root, but should prefer not to, if that is practical.

## Guidelines

* It may be preferable to update the database configuration on Server in place.  However, if that requires a large amount of work, it is acceptable to use existing command-line utilities or add new ones, which can be used to obtain a list of the pushed and published databases, delete them, and push and publish replacement ones at the same URLs that were used by the old ones.

### PR DESCRIPTION
**Pull request by float13**
migrate_fusion_hostname.py - A new script to automate the process of changing the Fusion hostname and fixing published databases.

*** THIS IS A WORK IN PROGRESS AND IS NOT COMPLETE YET. ***

Requires root permissions (sudo).

Reproduction Steps:
There is no specific bug or reproduction steps - this is a tool to automate the steps for changing the Fusion hostname. Thus, it performs many system changes and file deletions, so should only be used if necessary or on a test machine.

Unit tests can be run with migrate_fusion_hostname_unittest.py
These should be run with and without sudo. Some options are available in the unit tests to allow/disallow any permanent changes.
UNIT TESTS SHOULD NOT BE RUN ON A PRODUCTION MACHINE, ONLY ON A TEST MACHINE!

Tested on CentOS Linux 7 (Core), using the centos7geedev Virtualbox image.
Linux 3.10.0-862.14.4.el7.x86_64
with Python 2.7.5 

Fixes #782 (in progress)

### CODE REVIEW

**Comment by float13** [comment]
# migrate_fusion_hostname.py
Fixes #782 migrate fusion hostname

Douglas Brantner

Script to automate the process of changing the Fusion hostname and updating all pushed/published databases, according to the help documentation steps listed here:
http://www.opengee.org/geedocs/answer/172780.html

**Warning: Makes permanent system changes and deletes files - use with care!**
See the ```--dryrun``` flag for testing safely.

**The user must follow the instructions of the above link to re-publish databases**
Follow the instructions starting with "To change the server associations and publish the databases:"

## WIP Status:
- The ```--server_only``` mode is nearly complete (except for IP address updating).
- The ```--dev_machine``` (Fusion+Server) mode is not yet implemented, but reuses many of the functions of ```--server_only``` mode.
- Unit tests in ```migrate_fusion_hostname_unittest.py``` currently only test ```--dryrun``` mode (eg. no permanent changes are made).
- Full tests not completed yet (this requires setting up several VM's - if test machines with pre-built resources exist, this would be very helpful).

## To Run Unit Tests:
- ```cd``` to ```earthenterprise/earth_enterprise/src/fusion/tools``` and run:  
- ```python migrate_fusion_hostname_unittest.py```
The above tests should be run with and without ```sudo``` to test all cases.
Should be run with Python 2.7

## Usage:
Should be run with **Python 2.7** - adjust the following as needed for your system.
- ```python migrate_fusion_hostname.py -h``` to see list of all command line options or help.

The following commands use the ```--dryrun``` flag to run in a "test" mode and do not make any actual system changes.  
To run the program for real, omit the ```--dryrun``` flag. **WARNING: Will make permanent changes and delete files**
- ```python migrate_fusion_hostname.py --dryrun -s <current_hostname> <new_hostname>``` to change the hostname on a **GEE Server-Only** machine.
- Change ```-s``` to ```-d``` for a **GEE Fusion + GEE Server** machine (not yet implemented).
- The ```--override``` flag may be added to skip all user confirmation prompts **(always answers 'yes' to all prompts!)**.

**Comment by tst-ccamp** [comment]
@float13 Is this still a work in progress? What is left to complete it?

**Comment by float13** [comment]
@tst-ccamp The "WIP Status" from my Dec. 17 comment is still accurate. Someone familiar with the backend should probably look through it, before testing it "live", as there were a few things I wasn't sure about.

**Comment by tst-ccamp** [comment]
Since we don't have someone actively working this issue, I'm going to go ahead and close the pull request. Feel free to reopen if you would like to work more on it.

**Pull request closed without merging**
