### PR TITLE
WIP: Issue #361 Fusion UI: "Save and Build" as an additional file menu item

### PR DESCRIPTION
**Pull request by jnk7667**
#361 Fusion UI: "Save and Build" as an additional file menu item

### CODE REVIEW

**Comment by jnk7667** [comment]
I signed it!

**Comment by tst-rwildes** [comment]
Hi Joseph,  Did you mean for there to be more to this commit?  Or was this just a test run of an initial commit?

**Comment by jnk7667** [comment]
Hi Rick,

This commit was just as a clean slate for the new branch. I was taught this
was good practice for starting a new branch. I apologize for the confusion.


Sincerely,

Joseph Kent

**Comment by tst-rwildes** [comment]
No apologies needed.  Yes that is a good idea.  I just wanted to be sure it
was your intention.

**Comment by tst-ccamp** [comment]
@jnk7667 When creating PRs for something that is a work in progress we usually title like this: "WIP: Issue #XXX Descriptive name"

Please update when you get a chance. I'm going to add a section to the Developer contributions wiki page soon with some more info

**Pull request closed without merging**
