### PR TITLE
Fix python path for pywms server scripts.

### PR DESCRIPTION
**Pull request by bradh**
Completely untested.

### CODE REVIEW

**Comment by bradh** [comment]
Raised a new ticket for the removal: #118

**Comment by tst-ppenev** [comment]
Is it worth merging this, if we're going to delete the whole directory?

**Comment by bradh** [comment]
@tst-ppenev I'd like to, because deleting directories is likely to be more contentious, and it does keep showing up in my search.

**Comment by tst-ccamp** [comment]
Since @tst-lsavoie approved this already, that's good enough for me. I'll rebase and merge.

**Pull request merged**
