### PR TITLE
Fusion Installer/Uninstaller

### PR DESCRIPTION
**Pull request by arjntc1**
Contains updated fusion installer/uninstaller scripts -- tested against Ubuntu 14.04, 16.04 and RHEL 7.  Instructions for installing Fusion can be found on the wiki:

https://github.com/google/earthenterprise/wiki/Installing-Fusion

### CODE REVIEW

**Comment by tst-ccamp** [comment]
@asmitaw Can you post that you are OK with your commit being included to satisfy googlebot?

**Comment by bradh** [comment]
We are still missing the default textures (/opt/google/share/datasets/default.gedb) for fusion.

**Comment by bradh** [comment]
The server installer is assumed to still be in work. A quick test showed that the postgresql component of the install fails, and its creating gefusion init scripts instead of geserver init scripts.

**Comment by arjntc1** [comment]
Brad, I'll take a look at the missing texture/file.  Thanks for pointing out!

**Comment by asmitaw** [comment]
Yes, I am ok with this commit

**Comment by bradh** [comment]
@arjntc1 It looks like the installer script is fine, its just that the `scons ... -installdir=/tmp/fusion_os_install install` doesn't copy the dataset directories down. I manually added them to the `/tmp/fusion_os_install` tree (under `/tmp/fusion_os_install/fusion/opt/google/share`) and the install script copied them properly.

**Comment by arjntc1** [comment]
@bradh Yes, that is correct.  That is by design.  The data files are huge and it currently has to be an active choice.  Maybe a better choice would be to make it a command line argument and if the user chooses to copy the tutorial files, it could download it automatically.  Let me run that idea by a few people.  Thanks for the input!

**Comment by bradh** [comment]
@arjntc1 These aren't the tutorial files (which I agree should be optional, or at least only installed if the user has already download them). These are the background textures (maps) for fusion's main window - it won't run right without them.

**Comment by arjntc1** [comment]
@bradh Got it -- sorry for the misunderstanding.  I have updated the installer to include the copying of the datasets directory to the appropriate location.  Thanks again for pointing out!

**Comment by wangjunqin** [comment]
built earthenterprise on ubuntu 14.04 as step by build instruction in wiki  ,and then run  sudo ./install_fusion.sh,it show "df  ‘/gevol/assets ’No such file or directory,the  installer could not determine you machine's operating system"

**Comment by bradh** [comment]
@wangjunqin You could try removing the change to enable RedHat 7. If that works, try debugging what broke.

**Comment by arjntc1** [comment]
@wangjunqin Can you confirm you have the latest install_fusion.sh file?  The issue you spoke of is a bug in an older version of the install script, but you shouldn't see it now.

**Comment by tst-ccamp** [comment]
I've done some testing with this locally and gone through most of the code. So, I'm going to go ahead and approve/merge.

**Pull request merged**
