### PR TITLE
add apache rotatelogs binary to server install

### PR DESCRIPTION
**Pull request by tst-rwildes**
Addresses #1729 and adds rotatelogs binary to the install of Open GEE server

### CODE REVIEW

**Review by tst-nfarah-zz — COMMENTED** [review]
Let's create a ticket so we can link it to this PR

**Review by tst-nfarah-zz — APPROVED** [review]
Looks good

**Comment by tst-rwildes** [comment]
Hi @tst-nfarah the issue #1729 was created for this.

**Review by tst-blaird — APPROVED** [review]
Changes look good and I confirmed that the rotatelogs binary is no longer removed.

**Pull request merged**
