### PR TITLE
Merge docs from gh-pages into master

### PR DESCRIPTION
**Pull request by tst-lsavoie**
This PR pulls the gh-pages content into master, which eliminates duplicate documentation while allowing Github to produce the opengee.org website from the repo. Content specific to gh-pages was moved to the docs directory, and the geedocs directory (which was identical to earth_enterprise/docs/landing_page/manual/) was replaced with a symlink to earth_enterprise/docs/landing_page/manual/. I've verified that the website operates exactly the same with this change. You can see the new website here: https://tst-lsavoie.github.io/earthenterprise/ (spoiler: it's exactly the same as the old one).

Once this change is merged, we will have to update the project settings to pull the website source from /docs instead of the gh-pages branch.

This is a rework of PR #245.  The contents are exactly the same, but this version includes a merge commit showing that gh-pages is now merged into master.

### CODE REVIEW

**Comment by tst-lsavoie** [comment]
I'd recommend not squashing these commits when merging because we want the merge commit to show up in the reop.

**Comment by tst-lsavoie** [comment]
The googlebot is at it again.  Since this is a merge, all the commits from gh-pages are showing up.  Even though they're already in the repo, googlebot wants CLAs and confirmations from all authors.  @tst-ccamp, some of your commits show that you haven't signed a CLA, which is odd because others indicate that you have.  @tst-ccamp, @tst-ahernandez, @bradh - will each of you confirm in a comment that you are OK with your commits being included in this PR?

**Comment by tst-ccamp** [comment]
I've signed it

**Comment by tst-ccamp** [comment]
Looks like it somehow lost my CLA? I don't know how that happened. But, I signed a new one, so hopefully that will work.

**Comment by tst-ccamp** [comment]
Once this is merged, we can get @avnishb to update the gh-pages configuration. Also, after we verify everything is working, we should close the gh-pages branch so no one gets confused by it later on.

**Comment by tst-ahernandez** [comment]
I am okay with my commits being included.

**Comment by tst-lsavoie** [comment]
All the commits in this PR are already in the repo, so there's no need to have all the authors state that we can include their commits again.

**Pull request merged**
