### PR TITLE
Added 'package' scons target, calling out to gradlew to build RPM and DEB files

### PR DESCRIPTION
**Pull request by husf-dsheremata**

### CODE REVIEW

**Review by tst-mswartz — APPROVED** [review]
Tested, this works and builds the rpms

**Comment by tst-dsugar** [comment]
Should this include setup instructions for gradle, perhaps in BUILD.md?  Well, it might be argued then also in the new gee environment setup script too... (per #533 ).  Since this is the rhel rpm branch, it may not be critical for this yet...

**Review by tst-dsugar — COMMENTED** [review]
This is simple and straight-forward, other than lack of documentation...should updating the build/install instructions for setting up gradle be part of this ticket, or a follow-up one?

**Comment by tst-mswartz** [comment]
It seems to me that instructions for gradle should be added to the "build instructions" page on the wiki?

**Comment by tst-ppenev** [comment]
Setting up Gradle means making sure you have a JRE installed.  We should add that to the setup script.

**Comment by tst-ppenev** [comment]
Are we just waiting on mentioning the need for JRE to merge this?

**Review by tst-dsugar — APPROVED** [review]
We should do a small followup task to mention jre after this.

**Comment by tst-ppenev** [comment]
Yes. @tst-ccamp: can we merge this, and add a follow-up to mention JRE and add it to the build environment script?

**Pull request merged**
