### PR TITLE
changes to script to reflect NATIVE type build.

### LINKED ISSUE #229: update_bin.sh scripts is not updated for NATIVE build path
update_bin.sh scripts is not updated for NATIVE build path

refer  - src/update_bin.sh

### PR DESCRIPTION
**Pull request by asmitaw**
resolves #229

### CODE REVIEW

**Comment by tst-lsavoie** [comment]
Is this script still used?  I suppose it may still have some utility, but I've switched to just running the installer every time I want to test a new build.

**Comment by asmitaw** [comment]
@tst-lsavoie -yes I used it a couple times.

**Comment by tst-ccamp** [comment]
Already an approval, so merging

**Comment by andreisel** [comment]
This script is very useful for testing when you modify C++ modules. 
And two more scripts when you modify Python code in server/wsgi stuff
[update_wsgi.sh](https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/server/wsgi/update_wsgi.sh)

**Pull request merged**
