### PR TITLE
Remove the use of PIP from the source

### PR DESCRIPTION
**Pull request by tst-dmendyke**
Remove the need to use PIP when building.  This amounts to a documentation chance and the file .travis.yml in Open GEE needed to be changed.

### CODE REVIEW

**Comment by tst-ccamp** [comment]
Apparently it's been a while since anyone cleared the travis build cache. Looks like .travis.yml is missing the cmake dependency. You didn't introduce this bug, but unfortunately it's a blocker for verifying your changes. Please also add cmake as a dependent package. Failed build: https://travis-ci.org/google/earthenterprise/builds/341233885?utm_source=github_status&utm_medium=notification

**Comment by tst-dmendyke** [comment]
I changed .travis.yml in Open GEE and had already pushed the changes.  My
team discussed this during our daily scrum meeting.

**Comment by tst-ccamp** [comment]
@tst-dmendyke I don't really understand what you're saying. This pull request is still pending. It has to be approved by two people before it is merged.

**Comment by tst-lsavoie** [comment]
Closing - changes are included in PR #713.

**Pull request closed without merging**
