### PR TITLE
eliminate unnecessary update calls from autogen code

### PR DESCRIPTION
**Pull request by tst-basilhuffman**
initial commit

### CODE REVIEW

**Comment by tst-lsavoie** [comment]
@tst-basilhuffman I just thought of something. It's possible that we're only seeing failures from the RasterProject code because that's the only code we're testing. It may be that my original suggestion to try this optimization is misguided and it's broken everywhere, and we just haven't noticed it because we're focused on imagery projects. Can you list all the autogenerated files that are affected by this change? We may need to come up with additional tests cases to hit all of them.

**Comment by tst-basilhuffman** [comment]
@tst-lsavoie 
RasterProjectAssetD.cpp
RasterProductAssetD.cpp
MercatorRasterProductAssetD.cpp
VectorLayerXAssetD.cpp
MapLayerAssetD.cpp
MercatorRasterProjectAssetD.cpp

**Comment by tst-lsavoie** [comment]
We're probably hitting RasterProject and RasterProduct but almost certainly not the others. While testing this PR we'll need to make sure we're exercising all the code that has changed.

**Comment by tst-jkent** [comment]
Minor:
The indentation of the condition statements in the auto-generated code is off.
capture
capture2

**Pull request closed without merging**
