### PR TITLE
WMS server crash #1927

### LINKED ISSUE #1927: Segmentation fault can occur when accessing transparent tiles
**Describe the bug**

A segmentation fault can happen when accessing transparent tiles in GEE Server.

**To Reproduce**

1. Create a database with some transparent tiles
1. Pan and zoom into an area that has both transparent and non-transparent tiles in Mercator map

Receive this error in the server `error_log` file:
``` 
ERROR 10: Pointer 'hDS' is NULL in 'GDALGetRasterCount'.

[Thu Mar 25 10:53:54.337808 2021] [core:notice] [pid 32369:tid 140536558585728] AH00051: child pid 113 exit signal Segmentation fault (11), possible coredump in /opt/google/gehttpd
```

Server returns 404 errors when trying to access tiles

**Expected behavior**

No errors and return tiles properly

### PR DESCRIPTION
**Pull request by tst-ccamp**
Fixes #1927

### CODE REVIEW

**Comment by tst-ccamp** [comment]
@googlebot I consent.

**Comment by tst-dsugar** [comment]
> @googlebot I consent.

It looks like @tst-jlarocco  has to also...

**Comment by tst-jlarocco** [comment]
@googlebot I consent.

**Review by tst-basilhuffman — APPROVED** [review]

**Comment by tst-basilhuffman** [comment]
reviewed and tested, lgtm

**Review by tst-dsugar — APPROVED** [review]

**Pull request merged**
