### PR TITLE
Removed issue where fusion backed up data even when there was no data …  Fixes issue #126

### PR DESCRIPTION
**Pull request by nabsak**
Fixed fusion installer so that it wouldn't back up the first time fusion ever ran

### CODE REVIEW

**Comment by tst-ppenev** [comment]
Hi, @nabsak.  Thanks for the pull request.  Is this a fix for issue #126?

**Comment by tst-rwildes** [comment]
@nabsak can you sign the Contributor License Agreement (CLA)?  In the mean time I'll pull this PR locally and test it.  Probably do it in the morning.

**Comment by nabsak** [comment]
I did sign the CLA - it says "CLAs are signed, but unable to verify author consent". I'll fix the issue and push it to the repo.

**Comment by nabsak** [comment]
I guess it was an email issue - fixed!

**Pull request merged**
