### PR TITLE
Updated variables (#1861)

### LINKED ISSUE #1861: Invalid variables when reporting postgres errors
There are several variable naming errors in the function `_GetAllAssets` in `earth_enterprise/src/server/wsgi/serve/publish/publish_manager_helper.py`. Here is a part of the function:

```
    except psycopg2.Warning as w:
      logger.error(w)
      http_io.ResponseWriter.AddJsonFailureBody(response, str(e))
    except psycopg2.Error as e:
      logger.error(e)
      http_io.ResponseWriter.AddJsonFailureBody(response, str(w))
```
Note that in the first `except` statement the variable is called `w`, but in the Json response it is using the variable `e`. In the second `except` statement it has the same problem in reverse. We need to clean this up so that it always uses the correct variable.

### PR DESCRIPTION
**Pull request by augustocamaral2003**
Fixes #1861

### CODE REVIEW

**Comment by augustocamaral2003** [comment]
@googlebot I signed it!

**Comment by tst-lsavoie** [comment]
@augustocamaral2003 thanks for the PR. I'll work on getting it reviewed.

**Review by tst-lsavoie — APPROVED** [review]
The code changes look fine. I haven't tested it.

**Comment by tst-jlarocco** [comment]
@augustocamaral2003  Looks like there's one more spot (lines 1102 and 1105) where it has the 'w's and 'e's swapped.  Would you be able to grab that one also?

**Pull request closed without merging**
