### PR TITLE
Upgrade jquery

### PR DESCRIPTION
**Pull request by iparanza**
Upgrading jquery to 3.6.0 for STIG and CVE issues.

Verification Steps:

* Build gee and deploy server
* Verify jquery version in `/opt/google/gehttpd/htdocs/js/jquery.js` is 3.6.0

### CODE REVIEW

**Comment by tst-nfarah** [comment]
Let's link in the description the ticket this PR address if one does not exist. If it does not let' create it.

**Review by tst-nfarah — COMMENTED** [review]
Should we version the used jquery.min.js and jquery.js in their name, that way we know what version they are/were ? (e.g: add version to the name of the .js files)

**Comment by tst-nfarah** [comment]
Let's add verification steps for a reviewer/tester to follow.

**Comment by iparanza** [comment]
> Should we version the used jquery.min.js and jquery.js in their name, that way we know what version they are/were ? (e.g: add version to the name of the .js files)

That might be out of scope for this PR. This was just to upgrade jquery. If we want to version it that's going to require more work to update all of the jquery references in the code base.

**Comment by iparanza** [comment]
Resolves #1949

**Review by tst-mbiancalana — APPROVED** [review]
Code changes look good.

**Comment by iparanza** [comment]
Sorry found some more places in docs that used an old version of jquery. We also have several "versions" of the static fold for docs that seem to get moved depending on tag versions. I'm only updating the jquery file in the 5.3.8 geedocs folder.

**Comment by iparanza** [comment]
It's come to my understanding that docs are generated manually and pushed into the `geedocs` folder. The jquery version being packaged comes from using an old version of sphinx mentioned in the [build docs readme](https://github.com/google/earthenterprise/blob/master/docs/geedocs/docsrc/BUILD_DOCS.md). I'm going to back out the docs portion of this PR and submit another one to handle jquery in the docs.

**Review by tst-mbiancalana — APPROVED** [review]
Reviewed the current set of changes; re-approving.

**Pull request closed without merging**
